### ISSUE TITLE
Please make compatible to Kanboard version 1.0.37

### ISSUE THREAD

**Issue by poVoq** [aljawaid/Reporting#1]
There have been some minor changes in how the plugins are handled and this needs to be reflected in this plugin. Thanks.

**Comment by ThomasTJdev** [comment]
Hi @poVoq 

Would you please describe your problems? The plugin works fine for me with 1.0.37.

/ThomasTJdev

**Comment by poVoq** [comment]
if I install it manually it does not show up in the plugin list. I tried downgrading to 1.0.36 and there it works.
I think it is related to the new feature of setting a necessary version in the Plugin.php

**Comment by ThomasTJdev** [comment]
Okay, I'm going to test it on a clean install later today. Which of following ways do you mean be manual install?
1 - **Decompress the archive in the plugins folder**
or
2 - **Create a folder plugins/Reporting**
2 - **Copy all files under this directory**
or
3 - **Clone folder with git**

**Comment by poVoq** [comment]
Decompress the archive into the plugins folder (and rename it if necessary)

**Comment by ThomasTJdev** [comment]
Hi @poVoq 

I've just testet it on a clean Kanboard 1.0.37 installation with all the above methods - which worked.

If you download the ZIP file and extract it to the `plugins` folder, it is crucial that you rename the folder to **Reporting**.  
Please see below:

```bash
kbuser@machine:[/srv/http/kanboard]: ls plugins
    Reporting
```

```bash
kbuser@machine:[/srv/http/kanboard]: ls -l plugins/Reporting
    assets
    CHANGELOG
    Controller
    LICENSE
    Model
    Plugin.php
    README.md
    Reporting-master
    Schema
    screenshots
    Template
```

**Comment by ThomasTJdev** [comment]
@poVoq - Do you have an update?
